version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gcs
      - POSTGRES_PASSWORD=gcs
      - POSTGRES_DB=gcs_db
